"""create remates table

Revision ID: 493db3c355cd
Revises: c09a80de37f6
Create Date: 2026-07-13 23:30:12.673736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '493db3c355cd'
down_revision: Union[str, None] = 'c09a80de37f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remates',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('inmuebles', 'vehiculos', 'maquinaria_agricola', 'hacienda', 'arte_y_antiguedades', 'electronica', 'mobiliario', 'indumentaria', 'otros', name='remate_category'), nullable=False),
    sa.Column('cover_image_url', sa.String(length=2048), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'live', 'paused', 'finished', 'cancelled', name='remate_status'), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at', name=op.f('ck_remates_ends_at_after_starts_at')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_remates_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remates'))
    )
    op.create_index(op.f('ix_remates_owner_id'), 'remates', ['owner_id'], unique=False)
    op.create_index('ix_remates_status_starts_at', 'remates', ['status', 'starts_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_remates_status_starts_at', table_name='remates')
    op.drop_index(op.f('ix_remates_owner_id'), table_name='remates')
    op.drop_table('remates')
    # ### end Alembic commands ###
