"""gestion post remate y notificaciones

Revision ID: 50f830e27a57
Revises: 66eeccf174de
Create Date: 2026-07-23 14:34:06.428884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50f830e27a57'
down_revision: Union[str, None] = '66eeccf174de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('remate_id', sa.UUID(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_id_created_at', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_notifications_user_id_unread', 'notifications', ['user_id'], unique=False, postgresql_where=sa.text('read_at IS NULL'))
    op.create_table('postauction_cases',
    sa.Column('lote_id', sa.UUID(), nullable=False),
    sa.Column('remate_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('rematador_id', sa.UUID(), nullable=False),
    sa.Column('final_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('adjudicado', 'pendiente_contacto', 'pago_pendiente', 'pago_recibido', 'preparando_entrega', 'enviado', 'entregado', 'finalizado', name='postauction_status'), nullable=False),
    sa.Column('contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name=op.f('fk_postauction_cases_buyer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], name=op.f('fk_postauction_cases_lote_id_lotes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rematador_id'], ['users.id'], name=op.f('fk_postauction_cases_rematador_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['remate_id'], ['remates.id'], name=op.f('fk_postauction_cases_remate_id_remates'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_postauction_cases'))
    )
    op.create_index(op.f('ix_postauction_cases_buyer_id'), 'postauction_cases', ['buyer_id'], unique=False)
    op.create_index('ix_postauction_cases_rematador_id_status', 'postauction_cases', ['rematador_id', 'status'], unique=False)
    op.create_index(op.f('ix_postauction_cases_remate_id'), 'postauction_cases', ['remate_id'], unique=False)
    op.create_index('uq_postauction_cases_lote_id', 'postauction_cases', ['lote_id'], unique=True)
    op.create_table('postauction_timeline_entries',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('actor_role', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    # create_type=False: el tipo `postauction_status` ya lo crea la tabla
    # `postauction_cases` (columna `status`) más arriba en esta misma migración --
    # autogenerate no serializa este flag para `postgresql.ENUM`, se agrega a mano
    # (mismo ajuste que `Lote.category`/`remate_category`, ver 9757127dc38b).
    sa.Column('previous_status', postgresql.ENUM('adjudicado', 'pendiente_contacto', 'pago_pendiente', 'pago_recibido', 'preparando_entrega', 'enviado', 'entregado', 'finalizado', name='postauction_status', create_type=False), nullable=True),
    sa.Column('new_status', postgresql.ENUM('adjudicado', 'pendiente_contacto', 'pago_pendiente', 'pago_recibido', 'preparando_entrega', 'enviado', 'entregado', 'finalizado', name='postauction_status', create_type=False), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_postauction_timeline_entries_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['postauction_cases.id'], name=op.f('fk_postauction_timeline_entries_case_id_postauction_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_postauction_timeline_entries'))
    )
    op.create_index('ix_postauction_timeline_entries_case_id_occurred_at', 'postauction_timeline_entries', ['case_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_postauction_timeline_entries_occurred_at'), 'postauction_timeline_entries', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_postauction_timeline_entries_occurred_at'), table_name='postauction_timeline_entries')
    op.drop_index('ix_postauction_timeline_entries_case_id_occurred_at', table_name='postauction_timeline_entries')
    op.drop_table('postauction_timeline_entries')
    op.drop_index('uq_postauction_cases_lote_id', table_name='postauction_cases')
    op.drop_index(op.f('ix_postauction_cases_remate_id'), table_name='postauction_cases')
    op.drop_index('ix_postauction_cases_rematador_id_status', table_name='postauction_cases')
    op.drop_index(op.f('ix_postauction_cases_buyer_id'), table_name='postauction_cases')
    op.drop_table('postauction_cases')
    op.drop_index('ix_notifications_user_id_unread', table_name='notifications', postgresql_where=sa.text('read_at IS NULL'))
    op.drop_index('ix_notifications_user_id_created_at', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
    # Ajuste manual: `op.drop_table` no dispara `DROP TYPE` para columnas ENUM (mismo
    # motivo documentado en 9757127dc38b para `lote_status`) -- `postauction_status` lo
    # crea esta migración (la columna `status` de `postauction_cases`), así que su
    # downgrade debe eliminarlo explícitamente, después de dropear ambas tablas que lo
    # referencian.
    postgresql.ENUM(name="postauction_status").drop(op.get_bind(), checkfirst=True)
