"""add state engine audit columns to lotes

Revision ID: 588fe3c03f26
Revises: 9757127dc38b
Create Date: 2026-07-14 13:31:50.199883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588fe3c03f26'
down_revision: Union[str, None] = '9757127dc38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lotes', sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lotes', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lotes', sa.Column('final_price', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('lotes', sa.Column('cancellation_reason', sa.String(length=500), nullable=True))
    op.add_column('lotes', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    # Ajuste manual: autogenerate no detecta CheckConstraint nuevos (limitación conocida
    # de Alembic), así que se agrega a mano el que sí existe en el modelo
    # (app/modules/remates/lotes/models.py, Módulo 2.3).
    op.create_check_constraint(
        'ck_lotes_final_price_positive', 'lotes', 'final_price IS NULL OR final_price > 0'
    )


def downgrade() -> None:
    # Debe ir antes que el drop_column de 'final_price': el CheckConstraint referencia
    # esa columna, y Postgres no permite borrarla mientras el constraint exista.
    op.drop_constraint('ck_lotes_final_price_positive', 'lotes', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lotes', 'cancelled_at')
    op.drop_column('lotes', 'cancellation_reason')
    op.drop_column('lotes', 'final_price')
    op.drop_column('lotes', 'closed_at')
    op.drop_column('lotes', 'opened_at')
    # ### end Alembic commands ###
