"""create chat_messages table

Revision ID: 664d7402346d
Revises: 9d61c4f0e7c2
Create Date: 2026-07-20 18:49:57.146956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '664d7402346d'
down_revision: Union[str, None] = '9d61c4f0e7c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('remate_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('user', 'system', name='chat_message_kind'), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('author_role', sa.String(length=20), nullable=True),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('system_event_type', sa.String(length=50), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('source_event_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_chat_messages_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_chat_messages_deleted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['remate_id'], ['remates.id'], name=op.f('fk_chat_messages_remate_id_remates'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index(op.f('ix_chat_messages_remate_id'), 'chat_messages', ['remate_id'], unique=False)
    op.create_index('ix_chat_messages_remate_id_created_at', 'chat_messages', ['remate_id', 'created_at'], unique=False)
    op.create_index('uq_chat_messages_source_event_id', 'chat_messages', ['source_event_id'], unique=True, postgresql_where=sa.text('source_event_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_chat_messages_source_event_id', table_name='chat_messages', postgresql_where=sa.text('source_event_id IS NOT NULL'))
    op.drop_index('ix_chat_messages_remate_id_created_at', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_remate_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
    # Ajuste manual: `op.drop_table` no dispara el DDL de `DROP TYPE` para columnas ENUM
    # (mismo ajuste que la migración 9d61c4f0e7c2 del Módulo 2.4) -- `chat_message_kind`
    # es un tipo nuevo de esta migración, así que su downgrade debe eliminarlo explícitamente.
    postgresql.ENUM(name="chat_message_kind").drop(op.get_bind(), checkfirst=True)
