"""agrega cuenta regresiva y cierre automatico de lotes

Revision ID: 66eeccf174de
Revises: a1b2c3d4e5f6
Create Date: 2026-07-23 02:31:43.146061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66eeccf174de'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Épica 8, "cuenta regresiva y cierre automático de lotes" (ADR-007/ADR-043).
    # `timer_auto_close_enabled` es NOT NULL: necesita `server_default` para que las
    # filas de `lotes` ya existentes (si las hay) queden en `true` -- mismo valor que
    # el default de Python (`Lote.timer_auto_close_enabled`), que solo rige para filas
    # nuevas insertadas después de esta migración.
    op.add_column('lotes', sa.Column('timer_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lotes', sa.Column('timer_paused_remaining_seconds', sa.Integer(), nullable=True))
    op.add_column(
        'lotes',
        sa.Column(
            'timer_auto_close_enabled',
            sa.Boolean(),
            server_default=sa.text('true'),
            nullable=False,
        ),
    )
    op.create_index('ix_lotes_open_timer_ends_at', 'lotes', ['timer_ends_at'], unique=False, postgresql_where=sa.text("status = 'open' AND timer_ends_at IS NOT NULL"))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lotes_open_timer_ends_at', table_name='lotes', postgresql_where=sa.text("status = 'open' AND timer_ends_at IS NOT NULL"))
    op.drop_column('lotes', 'timer_auto_close_enabled')
    op.drop_column('lotes', 'timer_paused_remaining_seconds')
    op.drop_column('lotes', 'timer_ends_at')
    # ### end Alembic commands ###
