"""create lotes table

Revision ID: 9757127dc38b
Revises: 493db3c355cd
Create Date: 2026-07-14 12:52:31.986656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9757127dc38b'
down_revision: Union[str, None] = '493db3c355cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotes',
    sa.Column('remate_id', sa.UUID(), nullable=False),
    sa.Column('lot_number', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    # create_type=False: el tipo `remate_category` ya lo crea la migración 493db3c355cd
    # (tabla remates) — ADR-014 reutiliza el mismo enum nativo para Lote. Autogenerate no
    # serializa este flag para postgresql.ENUM, así que se agrega a mano (mismo ajuste
    # que app/modules/remates/lotes/models.py).
    sa.Column('category', postgresql.ENUM('inmuebles', 'vehiculos', 'maquinaria_agricola', 'hacienda', 'arte_y_antiguedades', 'electronica', 'mobiliario', 'indumentaria', 'otros', name='remate_category', create_type=False), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_label', sa.String(length=50), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('min_increment', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reserve_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'open', 'closed_sold', 'closed_unsold', 'cancelled', name='lote_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('base_price > 0', name=op.f('ck_lotes_base_price_positive')),
    sa.CheckConstraint('min_increment > 0', name=op.f('ck_lotes_min_increment_positive')),
    sa.CheckConstraint('quantity >= 1', name=op.f('ck_lotes_quantity_at_least_one')),
    sa.CheckConstraint('reserve_price IS NULL OR reserve_price >= base_price', name=op.f('ck_lotes_reserve_price_gte_base_price')),
    sa.ForeignKeyConstraint(['remate_id'], ['remates.id'], name=op.f('fk_lotes_remate_id_remates'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lotes'))
    )
    op.create_index(op.f('ix_lotes_remate_id'), 'lotes', ['remate_id'], unique=False)
    op.create_index('ix_lotes_remate_id_display_order', 'lotes', ['remate_id', 'display_order'], unique=False)
    op.create_index('uq_lotes_remate_id_lot_number', 'lotes', ['remate_id', 'lot_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_lotes_remate_id_open_status', 'lotes', ['remate_id'], unique=True, postgresql_where=sa.text("status = 'open' AND deleted_at IS NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_lotes_remate_id_open_status', table_name='lotes', postgresql_where=sa.text("status = 'open' AND deleted_at IS NULL"))
    op.drop_index('uq_lotes_remate_id_lot_number', table_name='lotes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_lotes_remate_id_display_order', table_name='lotes')
    op.drop_index(op.f('ix_lotes_remate_id'), table_name='lotes')
    op.drop_table('lotes')
    # ### end Alembic commands ###
    # Ajuste manual: `op.drop_table` no dispara el DDL de `DROP TYPE` para columnas
    # ENUM (Alembic construye un Table ad-hoc sin ese conocimiento) — a diferencia de
    # `remate_category` (create_type=False, no es dueño del tipo), `lote_status` SÍ lo
    # crea esta migración, así que su downgrade debe eliminarlo explícitamente.
    postgresql.ENUM(name="lote_status").drop(op.get_bind(), checkfirst=True)
