"""create ofertas table

Revision ID: 9d61c4f0e7c2
Revises: 588fe3c03f26
Create Date: 2026-07-14 14:23:23.175606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9d61c4f0e7c2'
down_revision: Union[str, None] = '588fe3c03f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ofertas',
    sa.Column('lote_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('accepted', 'rejected', 'outbid', 'winning', name='oferta_status'), nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('client_token', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_ofertas_amount_positive')),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name=op.f('fk_ofertas_buyer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], name=op.f('fk_ofertas_lote_id_lotes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ofertas'))
    )
    op.create_index(op.f('ix_ofertas_buyer_id'), 'ofertas', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_ofertas_lote_id'), 'ofertas', ['lote_id'], unique=False)
    op.create_index('ix_ofertas_lote_id_created_at', 'ofertas', ['lote_id', 'created_at'], unique=False)
    op.create_index('uq_ofertas_buyer_id_client_token', 'ofertas', ['buyer_id', 'client_token'], unique=True, postgresql_where=sa.text('client_token IS NOT NULL'))
    op.create_index('uq_ofertas_lote_id_accepted', 'ofertas', ['lote_id'], unique=True, postgresql_where=sa.text("status = 'accepted'"))
    op.create_index('uq_ofertas_lote_id_winning', 'ofertas', ['lote_id'], unique=True, postgresql_where=sa.text("status = 'winning'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_ofertas_lote_id_winning', table_name='ofertas', postgresql_where=sa.text("status = 'winning'"))
    op.drop_index('uq_ofertas_lote_id_accepted', table_name='ofertas', postgresql_where=sa.text("status = 'accepted'"))
    op.drop_index('uq_ofertas_buyer_id_client_token', table_name='ofertas', postgresql_where=sa.text('client_token IS NOT NULL'))
    op.drop_index('ix_ofertas_lote_id_created_at', table_name='ofertas')
    op.drop_index(op.f('ix_ofertas_lote_id'), table_name='ofertas')
    op.drop_index(op.f('ix_ofertas_buyer_id'), table_name='ofertas')
    op.drop_table('ofertas')
    # ### end Alembic commands ###
    # Ajuste manual: `op.drop_table` no dispara el DDL de `DROP TYPE` para columnas ENUM
    # (mismo ajuste que la migración 588fe3c03f26 del Módulo 2.3) — `oferta_status` es un
    # tipo nuevo de esta migración, así que su downgrade debe eliminarlo explícitamente.
    postgresql.ENUM(name="oferta_status").drop(op.get_bind(), checkfirst=True)
