"""create audit_log_entries table

Revision ID: a1b2c3d4e5f6
Revises: 664d7402346d
Create Date: 2026-08-03 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '664d7402346d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log_entries',
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('actor_role', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('remate_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_log_entries_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['remate_id'], ['remates.id'], name=op.f('fk_audit_log_entries_remate_id_remates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log_entries'))
    )
    op.create_index(op.f('ix_audit_log_entries_occurred_at'), 'audit_log_entries', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_actor_id'), 'audit_log_entries', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_action'), 'audit_log_entries', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_resource_type'), 'audit_log_entries', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_remate_id'), 'audit_log_entries', ['remate_id'], unique=False)
    op.create_index('ix_audit_log_entries_remate_id_occurred_at', 'audit_log_entries', ['remate_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_log_entries_remate_id_occurred_at', table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_remate_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_resource_type'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_action'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_actor_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_occurred_at'), table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    # ### end Alembic commands ###
