"""moderacion y administracion en tiempo real

Revision ID: ba429957efa3
Revises: 50f830e27a57
Create Date: 2026-07-23 15:56:55.309538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba429957efa3'
down_revision: Union[str, None] = '50f830e27a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remate_bans',
    sa.Column('remate_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('banned_by_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('banned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['banned_by_id'], ['users.id'], name=op.f('fk_remate_bans_banned_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['remate_id'], ['remates.id'], name=op.f('fk_remate_bans_remate_id_remates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_remate_bans_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remate_bans'))
    )
    op.create_index(op.f('ix_remate_bans_user_id'), 'remate_bans', ['user_id'], unique=False)
    op.create_index('uq_remate_bans_remate_id_user_id', 'remate_bans', ['remate_id', 'user_id'], unique=True)
    op.create_table('moderation_pinned_messages',
    sa.Column('remate_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('pinned_by_id', sa.UUID(), nullable=True),
    sa.Column('pinned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], name=op.f('fk_moderation_pinned_messages_message_id_chat_messages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pinned_by_id'], ['users.id'], name=op.f('fk_moderation_pinned_messages_pinned_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['remate_id'], ['remates.id'], name=op.f('fk_moderation_pinned_messages_remate_id_remates'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moderation_pinned_messages'))
    )
    op.create_index(op.f('ix_moderation_pinned_messages_remate_id'), 'moderation_pinned_messages', ['remate_id'], unique=False)
    op.create_index('uq_moderation_pinned_messages_message_id', 'moderation_pinned_messages', ['message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_moderation_pinned_messages_message_id', table_name='moderation_pinned_messages')
    op.drop_index(op.f('ix_moderation_pinned_messages_remate_id'), table_name='moderation_pinned_messages')
    op.drop_table('moderation_pinned_messages')
    op.drop_index('uq_remate_bans_remate_id_user_id', table_name='remate_bans')
    op.drop_index(op.f('ix_remate_bans_user_id'), table_name='remate_bans')
    op.drop_table('remate_bans')
    # ### end Alembic commands ###
