"""agrega garantias economicas para ofertar

Bloqueo (preautorización) de tarjeta vía Mercado Pago que una empresa puede exigir para
que un comprador oferte en su remate (opt-in por remate, `RemateSettings.guarantee_required`
en el JSONB de `remates.settings` -- no requiere columna nueva ahí). Ver
`app/modules/garantias/models.py` para el detalle de cada campo/índice.

`garantia_events` es insert-only, historial crudo de webhooks de Mercado Pago para
soporte/disputas.

Revision ID: df87311c1745
Revises: fee6961ace96
Create Date: 2026-09-16 13:29:06.237661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df87311c1745'
down_revision: Union[str, None] = 'fee6961ace96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garantias',
    sa.Column('remate_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending_authorization', 'active', 'captured', 'released', 'expired', 'failed', name='garantia_status'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('mp_payment_id', sa.String(length=50), nullable=True),
    sa.Column('mp_status', sa.String(length=30), nullable=True),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('captured_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_reason', sa.String(length=255), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name=op.f('fk_garantias_buyer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['remate_id'], ['remates.id'], name=op.f('fk_garantias_remate_id_remates'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_garantias')),
    sa.UniqueConstraint('remate_id', 'buyer_id', name='uq_garantias_remate_id_buyer_id')
    )
    op.create_index('ix_garantias_expires_at_active', 'garantias', ['expires_at'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index('ix_garantias_remate_id_active', 'garantias', ['remate_id'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_table('garantia_events',
    sa.Column('garantia_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['garantia_id'], ['garantias.id'], name=op.f('fk_garantia_events_garantia_id_garantias'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_garantia_events'))
    )
    op.create_index('ix_garantia_events_garantia_id_occurred_at', 'garantia_events', ['garantia_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_garantia_events_occurred_at'), 'garantia_events', ['occurred_at'], unique=False)
    # ### end Alembic commands ###
    # NOTA: autogenerate también detectó `bot_profiles`/`bot_remate_selections`/
    # `bot_simulation_runs` como "removidas" -- son tablas que existen en la base pero ya
    # no tienen modelo importado en `app/db/base.py` (deriva preexistente, ajena a esta
    # migración). Se removieron esas sentencias a mano: esta migración solo agrega lo de
    # garantías, no toca esas tablas.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_garantia_events_occurred_at'), table_name='garantia_events')
    op.drop_index('ix_garantia_events_garantia_id_occurred_at', table_name='garantia_events')
    op.drop_table('garantia_events')
    op.drop_index('ix_garantias_remate_id_active', table_name='garantias', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_garantias_expires_at_active', table_name='garantias', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('garantias')
    # ### end Alembic commands ###
    # Ajuste manual: `op.drop_table` no dispara `DROP TYPE` para columnas ENUM (mismo
    # motivo documentado en 9757127dc38b/50f830e27a57) -- `garantia_status` lo crea esta
    # migración (la columna `status` de `garantias`), así que su downgrade debe
    # eliminarlo explícitamente, después de dropear la tabla que lo referencia.
    postgresql.ENUM(name="garantia_status").drop(op.get_bind(), checkfirst=True)
